<!DOCTYPE html>
<html>
<body>
<h1>New User</h1>
<div>
    <a href="/users">users list</a>
</div>
<br>

<!-- BEGIN -->
<form enctype="multipart/form-data" action="/users" method="post">
    <div>
        <b>Name</b>
        <input type="text" name="user[name]" value="<?= $user['name'] ?>">
    </div>

    <br>

    <div>
       Avatar
        <input type="file" name="user[avatar]">
        <?php if(isset($errors['avatar'])): ?>
            <div style="color: red"><?= $errors['avatar'] ?></div>
        <?php endif; ?>
    </div>
    <br>
    <div>
        <input type="submit">
    </div>
    <br>
</form>

<!-- END -->
</body>
</html>